version: "3.7"

services:
  app:
    image: learning-docker/node:v1
    volumes:
      - ./:/app
    environment: # phần này ta định nghĩa ở file .env nhé
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
    ports:
      - "3000:3000"
    restart: unless-stopped
